### ISSUE TITLE
Possible weird behavior in `mapAndAccumulate`

### ISSUE THREAD

**Issue by ringvold** [dillonkearns/elm-markdown#117]
I get some weird behavior when using `mapAndAccumulate` in the Block module.

I have a custom `fn` tag which contains some child elements. Before rendering I am gathering these elements and trying to remove them from the current list of blocks to reinsert them later with some extra markup around it.

The problem is that when using `mapAndAccumulate` and returning some other elements (a comment or an empty paragraph) the blocks inside the tag is not removed but just lifted out of the tag and put after the block that is supposed to replace it.

The example under tries to replace the HtmlBlock of `fn` element (which has a paragraph with a link in it)  with a comment.
The expected result is to get a comment instead of the tag, but the actual result is a comment and then the block that where inside the tag. The same happens if some other Block type is used.

Is this expected behavior?

```elm
blocks
    |> Block.mapAndAccumulate
        (\soFar block ->
            case block of
                HtmlBlock (HtmlElement "fn" attrs _) ->
                    let
                        text =
                            attrs
                                |> List.filter (.name >> (==) "id")
                                |> List.map .value
                                |> List.head
                                |> Maybe.withDefault ""
                    in
                    ( Dict.insert text block soFar
                    , HtmlBlock (Block.HtmlComment "removed fn tag")
                    )

                 _ ->
                    ( soFar, block )
        )
        Dict.empty
```

**Comment by dillonkearns** [comment]
Could you give an executable example so we can make sure we're looking at the same thing? This one doesn't include any markdown so I have to guess at the context.

If I add this in the `BlockTransformTests` test cases then the test case here is green:

```elm
suite : Test
suite =
    describe "transform blocks"
        [ test "example" <|
            \() ->
                """<fn id="hello" />"""
                    |> Markdown.Parser.parse
                    |> Result.withDefault []
                    |> Block.mapAndAccumulate
                        (\soFar block ->
                            case block of
                                HtmlBlock (HtmlElement "fn" attrs _) ->
                                    let
                                        text =
                                            attrs
                                                |> List.filter (.name >> (==) "id")
                                                |> List.map .value
                                                |> List.head
                                                |> Maybe.withDefault ""
                                                |> Debug.log "id"
                                    in
                                    ( Dict.insert text block soFar
                                    , HtmlBlock (Block.HtmlComment "removed fn tag")
                                    )

                                _ ->
                                    ( soFar, block )
                        )
                        Dict.empty
                    |> Expect.equal
                        (Dict.fromList [("hello",HtmlBlock (HtmlElement "fn" [{ name = "id", value = "hello" }] []))],[HtmlBlock (HtmlComment "removed fn tag")]
                        )
]
```

**Comment by ringvold** [comment]
This should reproduce the issue:
```
test "do not extract blocks from inside HTML block" <|
            \() ->
                """<fn id="hello">[elm-pages](https://elm-pages.com/)</fn>"""
                    |> Markdown.Parser.parse
                    |> Result.withDefault []
                    |> Block.mapAndAccumulate
                        (\soFar block ->
                            case block of
                                HtmlBlock (HtmlElement "fn" attrs _) ->
                                    let
                                        text =
                                            attrs
                                                |> List.filter (.name >> (==) "id")
                                                |> List.map .value
                                                |> List.head
                                                |> Maybe.withDefault ""
                                                |> Debug.log "id"
                                    in
                                    ( Dict.insert text block soFar
                                    , HtmlBlock (Block.HtmlComment "removed fn tag")
                                    )

                                _ ->
                                    ( soFar, block )
                        )
                        Dict.empty
                    |> Expect.equal
                        ( Dict.fromList
                            [ ( "hello"
                              , HtmlBlock
                                    (HtmlElement "fn"
                                        [ { name = "id", value = "hello" } ]
                                        [ Block.Paragraph [ Link "https://elm-pages.com/" Nothing [ Text "elm-pages" ] ] ]
                                    )
                              )
                            ]
                        , [ HtmlBlock (HtmlComment "removed fn tag") ]
                        )
```

I know we talked about using attributes to avoid the wrapping of content in p-tags, but given that I do not mind the p-tag wrapping, putting markdown inside the tag should work, right?

**Comment by dillonkearns** [comment]
I'm still not following, what is the expected behavior and what is it doing instead?

> putting markdown inside the tag should work, right?

In what way is it not working? It seems like it's parsing it to a link, could you point me to the unexpected part?

**Comment by ringvold** [comment]
Executing the test should indicate the unexpected part.
To make it easier to spot the difference I will ignore the accumulated result because that is correct and just show the mapped blocks.

What I expect as a result:
```
[HtmlBlock (HtmlComment "removed fn tag")]
```

What actually happens:
```
[HtmlBlock (HtmlComment "removed fn tag"),Paragraph [Link "https://elm-pages.com/" Nothing [Text "elm-pages"]]])
```

When mapping the tag to some other block the content inside/children of the tag should not be included in the resulting list. In this case I only expect a `HtmlBlock (HtmlComment "removed fn tag")` in the list but what i get is the mapped block followed by the children of the tag it was mapped from. Like its been lifted out of the tag and become a sibling.

**Comment by ringvold** [comment]
Seems like that might be the expected behavior when looking at `foldl` which `mapAndAccumulate` uses.

**Comment by dillonkearns** [comment]
Yeah, I'm not quite sure if that's just the natural behavior for running `foldl` on the nested block structure, or if there's something off with the implementation. You can take a look and see if there's a way to tweak things that makes more sense: https://github.com/dillonkearns/elm-markdown/blob/65f3631874ff83de01aed1cfef3f8b2dabcfd7e4/src/Markdown/Block.elm#L899-L905.

It does seem counterintuitive, but I'm not sure if that's just the nature of running it on nested data like that or a mistake in the implementation there.

**Comment by ringvold** [comment]
Yeah, I'm not sure. Kind of depends on what you expect I guess. Maybe there could be a non-traversing fold in addition to the existing `foldl`? Would help my use case where I want to remove a block and its children. 😁

Changing the HtmlElement-case breakes the `traversal order is depth-first` test so I guess any changes should be additions?

**Comment by ringvold** [comment]
My fix for now is to copy the functions and modify them to my needs. :)
