### ISSUE TITLE
Strikethroughs

### ISSUE THREAD

**Issue by dillonkearns** [dillonkearns/elm-markdown#27]
Github-Flavored Markdown adds strikethroughs. The parsing for this will be similar to how other inlines are parsed:

https://github.com/dillonkearns/elm-markdown/blob/master/src/Markdown/Inlines.elm#L23-L39

And the inline style record will need to keep track of whether we are in a strikethrough:

https://github.com/dillonkearns/elm-markdown/blob/master/src/Markdown/Block.elm#L68-L75

Here's the current behavior:

https://github.com/dillonkearns/elm-markdown/blob/master/test-results/failing/GFM/%5Bextension%5D%20Strikethrough.md#example-491

Read more about it in [the Github-Flavored Markdown spec section on strikethrough](https://github.github.com/gfm/#strikethrough-extension-).

**Comment by thomasin** [comment]
i will pick this up

**Comment by dillonkearns** [comment]
Hey @thomasin! I'm glad you mentioned it, because actually I'm working on a big change to the inline parsing right now, and it changes the inline parsing code completely (using the inline parser from https://github.com/pablohirafuji/elm-markdown). Here's the branch: https://github.com/dillonkearns/elm-markdown/compare/rewrite-inlines.

So let's hold off on this ticket until I get that merged. I'm almost ready to merge it!

**Comment by dillonkearns** [comment]
Thanks for checking back on this project! It's great having you help out with getting these spec cases passing.

We're starting to get to the point where a lot of the main cases are going green, and the remaining noise will be some cases where we'll have to come up with some explicit goals about how `dillonkearns/elm-markdown` will differ from the CommonMark spec. I'm thinking it will only differ when it comes to how HTML is handled. I've got some ideas about this. Going to discuss at the community call next week.

By the way, did you see that on the Elm slack? Here are the details:

*Monday, March 2 @ 11am Pacific*

[Add to your Google calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=MTkwbmd2NWs2am5rZTJyOGJma3VkY2licjcgZGlsbG9ua2Vhcm5zLmNvbV80a3NnODljcmpmdmNoZHM2MHQxNmRwcXU5OEBn&tmsrc=dillonkearns.com_4ksg89crjfvchds60t16dpqu98%40group.calendar.google.com)

**Comment by dillonkearns** [comment]
And here's the agenda so far: https://gist.github.com/dillonkearns/0034a85ce8de293cc83c8e4aecdd30da

**Comment by thomasin** [comment]
Thanks for the update (-: Sounds good, I wasn't aware of the markdown channel. Will make some time to check out that diff and join the call.

**Comment by matheus23** [comment]
I was not aware of this channel either!
Can we mention it somewhere in the readme or perhaps in the contributing.md?

**Comment by dillonkearns** [comment]
@matheus23 great idea! Updated: https://github.com/dillonkearns/elm-markdown/commit/424925416cf2f4267e6630a6d5b893cbbf03cfab ✅

**Comment by tadityar** [comment]
> Thanks for checking back on this project! It's great having you help out with getting these spec cases passing.
> 
> We're starting to get to the point where a lot of the main cases are going green, and the remaining noise will be some cases where we'll have to come up with some explicit goals about how `dillonkearns/elm-markdown` will differ from the CommonMark spec. I'm thinking it will only differ when it comes to how HTML is handled. I've got some ideas about this. Going to discuss at the community call next week.
> 
> By the way, did you see that on the Elm slack? Here are the details:
> 
> _Monday, March 2 @ 11am Pacific_
> 
> [Add to your Google calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=MTkwbmd2NWs2am5rZTJyOGJma3VkY2licjcgZGlsbG9ua2Vhcm5zLmNvbV80a3NnODljcmpmdmNoZHM2MHQxNmRwcXU5OEBn&tmsrc=dillonkearns.com_4ksg89crjfvchds60t16dpqu98%40group.calendar.google.com)

Is this https://github.com/dillonkearns/elm-markdown/pull/46 the inline parser change that was blocking this issue? (and now that it's merge there's no more blocker on this?)

**Comment by dillonkearns** [comment]
Thank you for checking back on this @tadityar! I forgot to give an update here.

This is no longer blocked. The pull request I was referring to was #35, but you're right that #46 made some changes in that area as well.

And those are both merged and stable now. So you're welcome to pick this up if you're still interested @thomasin!

**Comment by thomasin** [comment]
Am happy for someone else to take this one (:
