### ISSUE TITLE
GFM Tables!

### ISSUE THREAD

**Issue by dillonkearns** [dillonkearns/elm-markdown#33]
This will be a really fun one I think (for those of us who find working on parsers fun 😉). Here are the relevant spec failures: https://github.com/dillonkearns/elm-markdown/blob/rewrite-inlines/test-results/failing/GFM/%5Bextension%5D%20Tables.md.

It would be best to create a separate module and unit test module to encapsulate these, then wire that into the top-level parser.

**Comment by stephenreddek** [comment]
After the live stream, I'm now further working on this feature here: https://github.com/stephenreddek/elm-markdown/tree/gfm-tables

**Comment by dillonkearns** [comment]
Woo! That's awesome, thanks so much for picking this up Stephen! Ping me on slack if you have any questions.

I've got it all wired in, but I commented out a the line that includes the parser at the top-level

https://github.com/dillonkearns/elm-markdown/blob/227e6e51af2d0284f563a2fb95ede1390548f716/src/Markdown/Parser.elm#L722-L723

And a test case:

https://github.com/dillonkearns/elm-markdown/blob/227e6e51af2d0284f563a2fb95ede1390548f716/tests/Tests.elm#L245-L260

And I'm completely ignoring the table rows here (just grabbing the header row in the current code):

https://github.com/dillonkearns/elm-markdown/blob/227e6e51af2d0284f563a2fb95ede1390548f716/src/Markdown/Parser.elm#L283-L296

Other than that, it should just be a matter of actually tweaking the table parser! 👍

**Comment by chazsconi** [comment]
Hi @stephenreddek - how are you getting on with this?  It would be really nice to be able to have tables as I need them for a project I am working on

**Comment by stephenreddek** [comment]
hi @chazsconi ! I'm sorry I haven't made progress on this in months. I've been feeling pretty burnt out and kind of stopped working on things outside of work. This gives me some more motivation to work on it (and perhaps even feel a bit rejuvenating to work on something fun)! Let me get into it this weekend and see what I can get done!

**Comment by chazsconi** [comment]
Great - thanks a lot!

**Comment by stephenreddek** [comment]
I've made some good progress on parsing regularly formatted tables. I haven't yet properly dealt with things like escaped pipes in tables, alignment, and block elements immediately following the table (usually an empty line is required, but the spec says a `>` should also break it).

**Comment by chazsconi** [comment]
@stephenreddek Thanks so much for working on this - I checked out your branch and it is all I need for my use case

**Comment by alltonp** [comment]
Would love to have basic table support.. is it possible to get this PR merged?

**Comment by dillonkearns** [comment]
Hello @alltonp! I've been coordinating with Stephen on Slack and we've been actively working to get it merged! Sorry for not doing a good job posting those updates in this thread, and thanks for the reminder to do that.

The current status of this PR is that the behavior is in great shape and the code is looking excellent. After doing some benchmarking, we found about a 10% degradation in the benchmark performance. The reason for the performance bottleneck is that the table parsing is very ambiguous so you have to try parsing tables for anything that could just be a regular paragraph.

So the fix is to just parse as a paragraph at the block-parsing level, then if you encounter a table delimiter row, you treat the previously parsed Paragraph block as a header.

So we're definitely actively working on getting this merged in! We'll keep you posted here.

**Comment by alltonp** [comment]
hi @dillonkearns, thank you for the update and also for such a great library, look forward to seeing table support soon!

**Comment by dillonkearns** [comment]
This is now supported in the latest version! See #52.
