### ISSUE TITLE
Setext headings

### ISSUE THREAD

**Issue by dillonkearns** [dillonkearns/elm-markdown#34]
Relevant section of the CommonMark spec: https://spec.commonmark.org/0.29/#setext-headings

Relevant failures: https://github.com/dillonkearns/elm-markdown/blob/rewrite-inlines/test-results/failing/GFM/Setext%20headings.md

**Comment by thomasin** [comment]
I will give this a go 👍

**Comment by dillonkearns** [comment]
Yay! That would be amazing, thank you @thomasin! Feel free to ping me at any point if you want to talk any ideas through (here, or Slack, or anywhere else) 👍
