### ISSUE TITLE
Give error message on URL with space

### ISSUE THREAD

**Issue by dillonkearns** [dillonkearns/elm-markdown#4]
Let's give an explicit error message in this case:

https://github.com/dillonkearns/elm-markdown/blob/master/test-results/failing/GFM/Links.md#example-485

The current behavior is that we are generating an invalid link (contains a space) (here's the test failure showing the current output: https://github.com/dillonkearns/elm-markdown/blob/master/test-results/failing/GFM/Links.md#example-485)

The error message should point out that if you want to explicitly have raw spaces in your URL, you can do so by surrounding the URL in `<>`s (see https://github.github.com/gfm/#example-498).

**Comment by thomasin** [comment]
i can try & do this (-:
