### ISSUE TITLE
Fenced code blocks

### ISSUE THREAD

**Issue by thomasin** [dillonkearns/elm-markdown#44]
Finish the fenced code blocks implementation  
Spec failures: https://github.com/dillonkearns/elm-markdown/blob/rewrite-inlines/test-results/failing/GFM/Fenced%20code%20blocks.md  

All fenced code block tests should pass

**Comment by thomasin** [comment]
I would like to pick this up 👍

**Comment by matheus23** [comment]
I guess there's a lot of changes happening in #43, just so you're aware :)

**Comment by thomasin** [comment]
Oh whoops I should have mentioned it sooner. Thanks for the heads up!

**Comment by folkertdev** [comment]
That's merged now. Still quite some failures in that category. Always happy to discuss the parser changes/speed quirks.

**Comment by dillonkearns** [comment]
I created a few more fine-grained issues with some context, so I'll close this issue and we can track the work there. Thanks all!

See #61 #62 #63 #64.
