### ISSUE TITLE
Handle numbered lists

### ISSUE THREAD

**Issue by dillonkearns** [dillonkearns/elm-markdown#5]
Example of some related failures:

* https://github.com/dillonkearns/elm-markdown/blob/master/test-results/failing/GFM/Lists.md#example-275
* https://github.com/dillonkearns/elm-markdown/blob/master/test-results/failing/GFM/Lists.md#example-272

**Comment by stephenreddek** [comment]
@dillonkearns I was thinking that I could take this on almost as a continuation of my other PR. It seems to me that the base `Block` type would rename the `List` to `UnorderedList` and then this PR would add `OrderedList`. Does this sound like an appropriate direction to pursue?

**Comment by dillonkearns** [comment]
Hi @stephenreddek, yes that sounds lovely! Thank you for asking, and thanks for your work on this! 🙏

Are you doing some Hacktoberfest coding, or just looking for a fun Elm project in general?

**Comment by stephenreddek** [comment]
A bit of both! I won't stop looking for fun elm projects after the month of October 😄. Unless you'd like to preserve some of these tasks for more contributors, I'll probably continue working on these as time allows. I find parsing particularly enjoyable.

**Comment by dillonkearns** [comment]
That's wonderful @stephenreddek! I would love your contributions!

I agree, it is really fun working on parsers, especially with the really nice `elm/parser` library. If there was more time in the day, I'd work on it even more! It was really hard getting the initial API working with the parsing of the inner HTML contents, but that was so fun. And then getting the initial markdown stuff was fun but a ton of work. And still, after all that, there is still a lot left! The markdown spec is just really big! The more contributors the merrier, and your contributions have been super thoughtful so it would be extra awesome to have more PRs from you! 😄 

I'll work on laying out a few more issues to try to find some good candidates (though you're welcome to just look through [the current GFM failures](https://github.com/dillonkearns/elm-markdown/tree/master/test-results/failing/GFM) as well for anything that seems fun)!

**Comment by stephenreddek** [comment]
@dillonkearns The way you've set up the spec to show the failures is very nice. That was well worth your effort!

Sounds great! Thank you

**Comment by dillonkearns** [comment]
This is fixed with #9 (package version 2.0.0) 🎉 Nice work! 😄
