### ISSUE TITLE
Fix minor heading parsing cases related to whitespace

### ISSUE THREAD

**Issue by dillonkearns** [dillonkearns/elm-markdown#58]
There are some heading-related spec test case failures:

https://github.com/dillonkearns/elm-markdown/blob/master/test-results/failing/GFM/ATX%20headings.md

## Summary of the Issues

The above link to the test results has links to the relevant sections of the spec. To summarize the current issues:

- At least one space is required between the # characters and the heading’s contents (https://spec.commonmark.org/0.29/#example-34)
- One to three spaces indentation are allowed (https://spec.commonmark.org/0.29/#example-38)
- Spaces are allowed after the closing sequence (https://spec.commonmark.org/0.29/#example-43)
- The closing sequence must be preceded by a space (https://spec.commonmark.org/0.29/#example-45)
- Backslash-escaped # characters do not count as part of the closing sequence (https://spec.commonmark.org/0.29/#example-46)

Any or all of these issues can be done as part of a pull request, so feel free to do a fix for one or more but skip some others here.

## The Code
The code is currently in the main parser module:

https://github.com/dillonkearns/elm-markdown/blob/c76fd356d1cea8040b1fd7ffcde4c6a928c1f50c/src/Markdown/Parser.elm#L858-L884

Optional, but it would make a lot of sense to extract this to a heading parser module.

There are some heading unit test cases here:

https://github.com/dillonkearns/elm-markdown/blob/bf44b0a7568bdef300c26dc55c8e4090b73491cc/tests/Tests.elm#L25-L34

It could be helpful to use those while working through some of these issues, but it's not necessary since they're covered by the end-to-end spec tests.

**Comment by pkeugine** [comment]
Hi! I've joined Incremental Elm server and saw this issue which I could work on. I'm not an expert but I'll begin with this issue and try my best :)

**Comment by dillonkearns** [comment]
@pkeugine that's great! Thank you for taking a look at this. I think this will be a great issue to get started with. Feel free to ping me if you have any questions!

**Comment by dillonkearns** [comment]
This was fixed in #76 #77 🎉
