### ISSUE TITLE
Nested lists are parsed as code block

### ISSUE THREAD

**Issue by Garados007** [dillonkearns/elm-markdown#73]
I have a problem to parse and render nested lists because they are rendered as a code block. 

For this

```markdown
1. List item
    - nested list item
    - other nested list item
2. Second list item
```

I expect this:

----
1. List item
    - nested list item
    - other nested list item
2. Second list item
----
 But I only got this:
![image](https://user-images.githubusercontent.com/12125053/102764994-4ce4c980-437c-11eb-982d-3564b86c4230.png)

I have created an [Ellie App](https://ellie-app.com/bRKYrMg3MSva1) with a minimum example. If I put a `Debug.log` statement right after the `Block`s are created I get this:
```
Heading H1 [Text "Example markdown"],OrderedList 1 [[Text "List item"]],CodeBlock { body = "- nested list item\n- other nested list item", language = Nothing },OrderedList 2 [[Text "Second list item"]]
```

**Comment by dillonkearns** [comment]
Hello @Garados007, thanks for the info. We're currently working on nested list parsing, and it's being tracked in #7. Keep an eye on that issue for updates! I'll close this issue to keep a single source of truth. Thanks!
