### ISSUE TITLE
Can't parse bold and empashized at the same time

### ISSUE THREAD

**Issue by NeoVier** [dillonkearns/elm-markdown#91]
If we try to parse something **strong** and *emphasized*, it should be ***strong and emphasized***, but it's only **strong**.

Here are some examples:

```elm
parse **bold** == Ok [Paragraph [Strong [Text "bold" ]]] -- Expected

parse *emphasis* == Ok [Paragraph [Emphasis [Text "emphasis"]]] -- Expected

parse ***both*** == Ok [Paragraph [Strong [Text "both"]]] -- Not expected. Should have `Emphasis` as well
```

**Comment by dillonkearns** [comment]
This is now fixed in the latest version!

Fixed by these commits:

b0d45a5a3bb6a57ffe37d6685e5d39250683bc23

f614759cf2ef470ecdb5fe6aaac3734e8eea5709

**Comment by dillonkearns** [comment]
Thank you for reporting the issue! 🙏
