### ISSUE TITLE
Can't parse some inlines padded with space

### ISSUE THREAD

**Issue by NeoVier** [dillonkearns/elm-markdown#94]
When parsing strong, emphasis or strikethrough that start and/or end with spaces, it gets parsed as a regular paragraph.

Here are some examples:

```elm
parse "**bold**" == Ok [Paragraph [Strong [Text "bold"]]] -- Expected
parse "** bold**" == Ok [Paragraph [Text " bold"]] -- Not expected, Should be [Paragraph [Strong [Text " bold"]]]
parse "**bold **" == Ok [Paragraph [Text "bold "]] -- Not expected. Should be [Paragraph [Strong [Text "bold "]]]
parse "** bold **" == Ok [Paragraph [Text " bold "]] -- Not expected. Should be [Paragraph [Strong [Text " bold "]]]
```

**Comment by dillonkearns** [comment]
I think this parsing is correct. Babelmark is a great tool to test out different implementations. For example 2:

https://babelmark.github.io/?text=**+bold**

The official GFM implementation outputs:

```html
<p>
  ** bold**
</p>
```

Which is exactly what `dillonkearns/elm-markdown` 7.0.0 parses to: https://ellie-app.com/f4CGtmC95Ksa1.

I believe all of these cases are correct.

**Comment by dillonkearns** [comment]
Based on the [spec section on emphasis and strong](https://github.github.com/gfm/#emphasis-and-strong-emphasis), and the results from babelmark, I believe the current implementation is correct for all these cases. So I'll close this issue, but if you find anything that I'm missing please let me know!

**Comment by NeoVier** [comment]
Hm, okay, that makes sense. Thanks for the explanation!
